# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 07:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharse', models.CharField(max_length=255)),
                ('translation', models.TextField(max_length=500)),
                ('show_count', models.PositiveIntegerField(blank=True, default=0)),
                ('test_count', models.PositiveIntegerField(blank=True, default=0)),
                ('test_rating', models.PositiveIntegerField(blank=True, default=0)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('translation', models.TextField(max_length=500)),
                ('show_count', models.PositiveIntegerField(blank=True, default=0)),
                ('test_count', models.PositiveIntegerField(blank=True, default=0)),
                ('test_rating', models.PositiveIntegerField(blank=True, default=0)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
