# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 04:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='user',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='time_added',
            new_name='time_created',
        ),
        migrations.RemoveField(
            model_name='word',
            name='show_count',
        ),
        migrations.RemoveField(
            model_name='word',
            name='test_count',
        ),
        migrations.RemoveField(
            model_name='word',
            name='test_rating',
        ),
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.AddField(
            model_name='word',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 20, 4, 44, 36, 86503, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Phrase',
        ),
    ]
