# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_word_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translated',
            field=models.BooleanField(default=False),
        ),
    ]
