# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_word_translated'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='base',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
