# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_word_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='translated',
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
    ]
