# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('translation', models.TextField(default=None, max_length=500, null=True)),
                ('base', models.CharField(default=None, max_length=255, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('frequency', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
