# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import main.models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160527_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pronounce',
            field=models.FileField(blank=True, default='', upload_to=main.utils.pronounce_full_path),
        ),
    ]
