# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_word_pronounce'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='gstatic',
            field=models.BooleanField(default=False),
        ),
    ]
