# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_word_gstatic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='gstatic',
            field=models.NullBooleanField(default=None),
        ),
    ]
