# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160528_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='test_rating',
            new_name='know_rating',
        ),
    ]
