# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20160531_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='know_rating',
        ),
        migrations.AddField(
            model_name='progress',
            name='answered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='ratio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='show_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
