# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160717_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['rank']},
        ),
        migrations.AlterField(
            model_name='progress',
            name='ratio',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=9),
        ),
    ]
