# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20160728_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='show_count',
            new_name='asked',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='answered',
            new_name='correct_answers',
        ),
    ]
