# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-28 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_progresslog_progresslogmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressLogManager',
        ),
        migrations.AddField(
            model_name='progresslog',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
