# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170128_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronounce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('translation', models.TextField(default=None, max_length=500, null=True)),
                ('base', models.CharField(default=None, max_length=255, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('frequency2', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('pronounce', models.FileField(blank=True, default='', upload_to=main.models.pronounce_full_path)),
                ('gstatic', models.NullBooleanField(default=None)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('translation', models.TextField(default=None, max_length=500, null=True)),
                ('base', models.CharField(default=None, max_length=255, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('frequency2', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('pronounce', models.FileField(blank=True, default='', upload_to=main.models.pronounce_full_path)),
                ('gstatic', models.NullBooleanField(default=None)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
