# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_pronounce_translation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pronounce',
            old_name='pronounce',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='pronounce',
            name='base',
        ),
        migrations.RemoveField(
            model_name='pronounce',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='pronounce',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='pronounce',
            name='frequency2',
        ),
        migrations.RemoveField(
            model_name='pronounce',
            name='gstatic',
        ),
        migrations.RemoveField(
            model_name='pronounce',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='pronounce',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='frequency2',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='gstatic',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='pronounce',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='rank',
        ),
        migrations.AddField(
            model_name='pronounce',
            name='status',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='translation',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
