# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20170201_0556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='WordOs',
        ),
        migrations.RenameModel(
            old_name='WordSecond',
            new_name='WordWf',
        ),
    ]
