# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20170203_0514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordos',
            options={},
        ),
        migrations.RemoveField(
            model_name='wordos',
            name='base',
        ),
        migrations.RemoveField(
            model_name='wordos',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='wordos',
            name='frequency2',
        ),
        migrations.RemoveField(
            model_name='wordos',
            name='gstatic',
        ),
        migrations.RemoveField(
            model_name='wordos',
            name='pronounce',
        ),
        migrations.RemoveField(
            model_name='wordos',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='wordos',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='wordos',
            name='time_updated',
        ),
        migrations.RemoveField(
            model_name='wordos',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='wordwf',
            name='base',
        ),
        migrations.RemoveField(
            model_name='wordwf',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='wordwf',
            name='time_updated',
        ),
        migrations.RemoveField(
            model_name='wordwf',
            name='translation',
        ),
    ]
