# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20170203_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronounce',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
