# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20170203_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['rank'], 'permissions': (('tester', 'Tester interfaces'),)},
        ),
    ]
