# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresslog',
            name='progress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Progress'),
        ),
    ]
