# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_progresslog_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='correct_seq',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
