# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_progress_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Word'),
        ),
    ]
