# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20170224_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='user_comment',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='user_translation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='user_word',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
