# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20170313_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
