# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_progress_time_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='added',
        ),
        migrations.AddField(
            model_name='progress',
            name='know_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='know_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='know_3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='know_4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='know_5',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='know_avg',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='progress',
            name='know_max',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
