# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_progress_know_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='know_sum',
            new_name='know_count',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='know_max',
            new_name='know_last',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='know_1',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='know_2',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='know_3',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='know_4',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='know_5',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='showed',
        ),
        migrations.AddField(
            model_name='progress',
            name='know_first',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
