# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20170417_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresslog',
            name='progress',
        ),
        migrations.DeleteModel(
            name='ProgressLog',
        ),
    ]
