# Generated by Django 2.2.24 on 2021-09-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_remove_progress_user_translation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pronounce',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.DeleteModel(
            name='WordOs',
        ),
        migrations.DeleteModel(
            name='WordWf',
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['rank']},
        ),
    ]
