# Generated by Django 2.2.24 on 2021-09-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20210918_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='explicit',
        ),
        migrations.AlterField(
            model_name='preferences',
            name='filters',
            field=models.CharField(default='', max_length=10),
        ),
    ]
